config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'items#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :items do
    resources :bookings, only: [:new, :create, :update, :edit, :index, :show, :index_as_renter]
  end
  resources :bookings, only: [:destroy]

  namespace :my do
    resources :items, only: [:index]
    resources :bookings, only: [:index, :update]
  end

  get '/bookings' => 'bookings#index_as_renter', :as => 'index_as_renter'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :item
  validates :start_day, presence: true
  validates :end_day, presence: true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_many_attached :photos
  validates :name, :description, :category, :price_per_day, :location, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :bookings
  has_many :items, dependent: :destroy
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :username])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: [:show, :edit, :update, :destroy]

  def index
    @item = Item.find(params[:item_id])
    @bookings = Booking.where(user_id: current_user.id)
  end

  def index_as_renter
    @bookings = Booking.where(user_id: current_user.id)
  end

  def show
    @item = @booking.item
  end

  def new
    @item = Item.find(params[:item_id])
    @booking = Booking.new
  end

  def create
    @item = Item.find(params[:item_id])
    @booking = Booking.new(booking_params)
    @booking.item = @item
    @booking.user = current_user
    if @booking.end_day && @booking.start_day
      @booking.total_price = (@booking.end_day - @booking.start_day).to_i * @booking.item.price_per_day.to_i
    else
      @booking.total_price = 0
    end
    if @booking.save
      redirect_to index_as_renter_path, notice: 'Booking was successfully created.'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @booking.update(booking_params)
      redirect_to item_path(@item), notice: 'Booking was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @booking.destroy
    redirect_to index_as_renter_path, notice: 'Booking was successfully deleted.'
  end

  private

  def set_booking
    @booking = Booking.find(params[:id])
  end

  def booking_params
    params.require(:booking).permit(:total_price, :start_day, :end_day, :user_id, :item_id)
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  skip_before_action :authenticate_user!, only: :index

  def index
    @items = Item.all
    if params[:what].blank? && params[:where].blank?
      @items = Item.all
    else
      # @items = Item.where(category: params[:what], location: "%#{params[:where]}%")
      @items = Item.where("location ILIKE ? AND category = ?", "%#{params[:where]}%", params[:what])
    end
  end

  def show
    @item = Item.find(params[:id])
    @user = User.find(@item.user_id)
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    @item.user = current_user
    if @item.save
      redirect_to item_path(@item)
    else
      render :new
    end
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if current_user == @item.user
      if @item.update(item_params)
        redirect_to item_path(@item), notice: 'Item was successfully updated.'
      else
        render :edit
      end
    else
      redirect_to items_path, notice: "You don't own this gear so you can't edit the details."
    end
  end

  def destroy
    @item = Item.find(params[:id])
    if current_user == @item.user
      @item.destroy
      redirect_to items_path, notice: 'Item was successfully deleted.'
    else
      redirect_to items_path, notice: "You don't own this gear so you can't delete it."
    end
  end

  private

  def item_params
    params.require(:item).permit(:name, :description, :category, :price_per_day, :location, :user_id, photos: [])
  end
end

app/controllers/my/bookings_controller.rb
class My::BookingsController < ApplicationController
  def index
    @items = current_user.items
  end

  def update
    set_booking
    @booking.update(set_params)
    redirect_to my_bookings_path
  end


  private

  def set_booking
    @booking = Booking.find(params[:id])
  end

  def booking_params
    params.require(:booking).permit(:total_price, :start_day, :end_day, :user_id, :item_id)
  end

end

app/controllers/my/items_controller.rb
class My::ItemsController < ApplicationController
  def index
    @items = current_user.items
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/index.html.erb
<div class="banner">
<!--   <h1> <%= @user.email %> Bookings</h1>
  <p><span id="banner-typed-text"></span></p>
</div> -->

<div class="container mt-4">
  <div class="cards">
    <% @bookings.each do |booking| %>
      <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= cl_image_path item.photo.key %>)">
        <div class="d-flex justify-content-between m-2">
          <div><%= link_to item.name, item_path(@item) %></div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/bookings/index_as_renter.html.erb
<div class="text-center mt-4">
  <h2> See all your <strong>bookings</strong> for items you are <strong>renting</strong>: </h2>
</div>

<div class="container mt-4">
  <div class="row">
    <div class="mt-4 col-sm-12 col-lg-6">
      <div class="cards">
        <% @bookings.each do |booking| %>
        <div class="booking-details">
          <ul class="list-unstyled hidden-sm hidden-xs padded">
            <li><strong>Booking ID: <%= booking.id %> - <%= booking.item.name %></strong></li>
            <li>Dates: <%= booking.start_day %> to <%= booking.end_day %></li>
            <li>Location: <%= booking.item.location %></li>
            <li>Total Price: <%= booking.total_price %> CHF</li>
          </ul>
        </div>
        <% end %>
      </div>
    </div>
  </div>
  <hr>
<%= link_to "Back to Home", items_path, class:"btn btn-default btn-lg " %>
</div>

app/views/bookings/new.html.erb
<div class="text-center mt-5"><h2>Book <%= @item.name %></h2></div>
<div class="container d-flex">
  <div class="container mt-5">
  <div class="row justify-content-center">
    <div class="mt-4 col-sm-12 col-lg-6">
      <h3>Select your rental start and end dates</h3>
        <%= simple_form_for [@item, @booking] do |f| %>
          <%= f.input :start_day %>
          <%= f.input :end_day %>
          <%= f.button :submit, class: "btn btn-success" %>
        <% end %>
    </div>
  </div>
<hr>
  <%= link_to 'Back to Item', item_path(@item), class: "btn btn-default btn-lg" %>
</div>

  <div class="container mt-5">
    <div class="row justify-content-center">
      <div class="mt-4 col-sm-12 col-lg-6">
        <h3>Booking Details</h3>
          <div class='product-body'>
          <p>Located in <strong><%= @item.location %></strong></p>
          <p><strong>Description:</strong> <%= @item.description%></p>
          <p><strong>Category:</strong> <%= @item.category%></p>
          <p><strong>Price Per Day:</strong> <%= @item.price_per_day %> CHF</p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/items/_form.html.erb
<%= simple_form_for(@item) do |f| %>

    <div class="form-inputs">
      <%= f.input :name, label: 'Tagline for your gear', hint: 'e.g. Amazing jogging stroller ready for adventures' %>
    </div>

    <div class="form-inputs">
      <%= f.input :description, label: 'Add a description', hint: 'Tell us a bit more about the features, condition, quirks, etc. ' %>
    </div>

    <div class="form-inputs">
      <%= f.input :category, collection: ['stroller/pram', 'hiking carrier/backpack','bike trailer'] %>
    </div>

    <div class="form-inputs">
      <%= f.input :location, label: 'Where can someone pick it up?', hint: 'Please only put city. Never your personal address.'%>
    </div>

    <div class="form-inputs">
      <%= f.input :price_per_day %>
    </div>

    <div class="form-inputs">
      <%= f.input :photos, as: :file, input_html: { multiple: true } %>
    </div>

    <div class="form-actions btn btn-primary mt-4">
      <%= f.button :submit %>
    </div>
  <% end %>
</div>

app/views/items/edit.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="mt-4 col-sm-12 col-lg-6">
      <h1><%= @item.name %></h1>

      <%= render 'form', item: @item %>
    </div>
  </div>
<hr>
  <%= link_to 'Back to My Items', my_items_path, class: "btn btn-default btn-lg" %>
</div>

app/views/items/index.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.0),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1526301352057-62f44bf4e826?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1352&q=80);">
  <div class="container">
    <h1>Mini Gear Lender</h1>
      <p>Rent gear. Lend gear. Have mini adventures.</p>
  </div>
</div>

<div class="container">
<h2>What are you looking for?</h2>
  <div class="container d-flex">
    <div class="container mb-1">
      <%= form_tag items_path, method: :get do %>
      <%= select_tag :what, options_for_select([ "","stroller/pram", "hiking carrier/backpack",  "bike trailer" ], "") %>
    </div>
​
    <div class="container mb-1">
      <%= submit_tag "Show me the gear!", class: "btn btn-primary" %>
    </div>
      <% end %>
  </div>
​</div>

  <div class="container m-7">
    <h2>Gear for rent</h2>
    <div class="cards">
      <% @items.each do |item| %>
        <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= cl_image_path item.photos.first.key %>)">
          <div class="d-flex justify-content-between m-2">
            <div><a><%= link_to item.name, item_path(item) %></a></div>
            </div>
          </div>
      <% end %>
    </div>
  </div>
​
  <% if user_signed_in? %>
    <div class="container mt-2">
      <%= link_to 'Add gear to lend', new_item_path, class:"btn btn-ghost" %>
    </div>
  <% end %>
​

app/views/items/new.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="mt-4 col-sm-12 col-lg-6">
      <%= render 'form', item: @item %>
    </div>
  </div>
</div>

app/views/items/show.html.erb
<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <%= cl_image_tag @item.photos.first.key, :height=>400, :crop=>"scale", :class=>"d-block w-100" %>
    </div>

    <% @item.photos.drop(1).each do |photo| %>
      <div class="carousel-item">
        <%= cl_image_tag photo.key, :height=>400, :crop=>"scale", :class=>"d-block w-100" %>
      </div>
    <% end %>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

<div class="container d-flex m-5">

  <div class="justify-content-around">
    <div class="mr-5 col-sm-12 col-lg-12">
      <h1><%= @item.name %></h1>
      <p><strong>Owner: </strong><%= @user.first_name %></p>
      <p><strong>Location: </strong><%= @item.location %></p>
      <p><strong>Category: </strong><%= @item.category %></p>
      <p><strong>Price per day: </strong><%= @item.price_per_day %> CHF</p>
      <h2>Description:</h2>
        <p><%= @item.description %></p>
        <%= link_to 'Booking', new_item_booking_path(@item), class: "btn btn-primary mt-4" %>
        <br>
        <br>
        <% if current_user == @item.user %>
        <%= link_to edit_item_path(@item) do %>
          <i class="fas fa-pencil-alt m-3" style="color: gray"></i>
          <% end %>
          <%= link_to item_path(@item),
                method: :delete,
                data: { confirm: "Are you sure?" } do %>
                <i class="fas fa-trash" style="color: gray"></i>
                <% end %>
        <% end %>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-12 col-lg-6">
        <!-- Map showing the location of the item -->
        <!-- <img id="map" src=https://api.mapbox.com/styles/v1/mapbox/streets-v11/static/2.3381,48.8693,10.45,0,0/600x1000?access_token=pk.eyJ1IjoiZXBhbGFuZGVyIiwiYSI6ImNrOGs5aHE3cjAzMmozbXA2NjIyY3VtbWsifQ.f96OEiie-0YcCe5xKQgtgw' -->
        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2702.518734250236!2d8.546746550995335!3d47.36279327906696!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x479aa7f798204207%3A0xee823a5ecdbfd65c!2sChainwork%20AG!5e0!3m2!1sde!2sch!4v1587631929495!5m2!1sde!2sch" width="600" height="450" frameborder="0" style="border:0;" allowfullscreen="" aria-hidden="false" tabindex="0"></iframe>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMiniGearLender</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/flashes' %>
    <%= render 'shared/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/my/bookings/index.html.erb
<div class="text-center mt-4">
  <h2> See all your <strong>bookings</strong> for items you are <strong>lending</strong>: </h2>
</div>

<div class="container mt-4">
  <div class="row">
    <div class="mt-4 col-sm-12 col-lg-6">
      <div class="cards">
      <% @items.each do |item| %>
        <% item.bookings.each do |booking| %>
        <div class="booking-details">
          <ul class="list-unstyled hidden-sm hidden-xs padded">
            <li><strong>Booking ID: <%= booking.id %> - <%= booking.item.name %></strong></li>
            <li>Dates: <%= booking.start_day %> to <%= booking.end_day %></li>
            <li>Location: <%= booking.item.location %></li>
            <li>Total Price: <%= booking.total_price %> CHF</li>
            <li class="text-left"><%= link_to "Cancel", booking_path(booking), method: :delete, class:"btn btn-primary", data: {confirm: "Are you sure"} %></li>
          </ul>
        </div>
        <% end %>
        <% end %>
      </div>
    </div>
  </div>
  <hr>
<%= link_to "Back to Home", items_path, class:"btn btn-default btn-lg " %>
</div>

app/views/my/items/index.html.erb
<div class="text-center mt-4">
  <h2>Here are all the <strong>items</strong> you have posted to lend!</h2>
</div>

<div class="container mt-4">
  <div class="row">
    <div class="mt-4 col-sm-12 col-lg-6">
      <% @items.each do |item| %>
        <div class='product-body'>
          <p><strong><%= item.name %></strong></p>
          <p>Located in <strong><%= item.location %></strong></p>
          <p><strong>Description:</strong> <%=item.description%></p>
          <p><strong>Price:</strong> <%= item.price_per_day %> CHF per day </p>
        </div>
      <ul class="list-unstyled hidden-sm hidden-xs padded">
        <li class="text-left">
          <%= link_to "Edit this item", edit_item_path(item), class:"btn btn-primary"%>
        </li>
      </ul>
      <% end %>
    </div>
  </div>
  <hr>
  <%= link_to "Back to Home", items_path, class:"btn btn-default btn-lg " %>
</div>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/shared/_flashes.html.erb
<div class="container">
  <% if notice %>
    <div class="alert alert-info alert-dismissible" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <%= notice %>
    </div>
  <% end %>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "/", class: "navbar-brand" do %>
    <%= image_tag "logo.png", class: "avatar"%>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div>
    <h3>Hello, <%= current_user.nil? ? 'Adventurer' : current_user.first_name %>!</h3>
  </div>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", "/", class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "menu_icon.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Add my Gear", new_item_path, class: "dropdown-item" %>
            <%= link_to "My Items to Lend", my_items_path, class: "dropdown-item" %>
            <%= link_to "My Bookings for My Lended Items", my_bookings_path, class: "dropdown-item" %>
            <%= link_to "My Bookings", index_as_renter_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>